/**
 * Capacitor native-sync drift detector — apps/native gradle ↔ installed plugins.
 *
 * pnpm's isolated linker bakes the exact resolved version + peer hash into the
 * .pnpm path that `apps/native/android/capacitor.settings.gradle` hardcodes
 * (the file is GENERATED by `cap sync`). If a `@capacitor/*` dependency is
 * bumped without re-running `cap sync`, the committed gradle keeps pointing at
 * the OLD store path — which no longer exists — and the Android build fails
 * late with an opaque Gradle error. This gate fails fast instead: every plugin
 * path in the generated gradle must (a) reference the version actually
 * installed, and (b) resolve to a real directory on disk.
 *
 * Runs in `pnpm test`, so it gates every CI run — mirroring the schema-parity /
 * drizzle-journal discipline.
 *
 * Fix when it fails:
 *   pnpm --filter @intake/web cap:export   # produce apps/web/out (webDir)
 *   pnpm --filter @intake/native sync       # regenerates capacitor.settings.gradle
 * then commit the regenerated file.
 *
 * Run: pnpm exec vitest run src/__tests__/capacitor-version-parity.test.ts
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

// apps/web/src/__tests__ -> repo root is four levels up.
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
const androidDir = resolve(repoRoot, "apps/native/android");
const settingsGradle = readFileSync(resolve(androidDir, "capacitor.settings.gradle"), "utf8");

// Each include embeds the pnpm store path, e.g.
//   new File('../../../node_modules/.pnpm/@capacitor+network@8.0.1_@capacitor+core@8.4.0/node_modules/@capacitor/network/android')
// Capture the leading plugin package (right after `.pnpm/`), its version, and
// the relative projectDir so we can confirm it resolves.
interface PluginRef {
  name: string;
  version: string;
  projectDir: string;
}
const refs: PluginRef[] = [];
for (const m of settingsGradle.matchAll(
  /new File\('([^']*\.pnpm\/@capacitor\+([a-z-]+)@([^_/'\s]+)[^']*)'\)/g
)) {
  const [, projectDir, name, version] = m;
  if (projectDir && name && version) refs.push({ projectDir, name, version });
}

describe("capacitor native-sync parity (apps/native)", () => {
  it("capacitor.settings.gradle declares the synced native plugins", () => {
    expect(refs.length).toBeGreaterThan(0);
    // The platform is always present; sanity-check it parsed.
    expect(refs.map((r) => r.name)).toContain("android");
  });

  it.each(refs)(
    "@capacitor/$name@$version matches the installed version and resolves on disk",
    ({ name, version, projectDir }) => {
      const installed = (
        JSON.parse(
          readFileSync(
            resolve(repoRoot, "apps/native/node_modules/@capacitor", name, "package.json"),
            "utf8"
          )
        ) as { version: string }
      ).version;
      expect(
        version,
        `capacitor.settings.gradle pins @capacitor/${name}@${version} but ${installed} is installed — run cap sync (see this file's header)`
      ).toBe(installed);
      expect(
        existsSync(resolve(androidDir, projectDir)),
        `capacitor.settings.gradle projectDir does not resolve: ${projectDir} — run cap sync`
      ).toBe(true);
    }
  );
});
